title: The Fuzzing Book
author: Andreas Zeller, Rahul Gopinath, Marcel Böhme, Gordon Fraser, and Christian Holler
copyright: 2021-2025 CISPA Helmholtz Center for Information Security (www.cispa.de); © Copyright 2018-2020 Saarland University, authors, and contributors. All Rights Reserved
logo: "_static/fuzzingbook.png"

bibtex_bibfiles:
  - fuzzingbook.bib

latex:
  latex_documents:
     targetname: fuzzingbook.tex

sphinx:
  config:
    latex_engine: xelatex
    latex_show_pagerefs: true
    latex_show_urls: footnote

execute:
  execute_notebooks: 'off'
  stderr_output: show
  timeout: 300

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist
    - deflist

html:
  announcement: '<p>This is a beta version of fuzzingbook.org, currently in development. See the <a href="https://fuzzingbook.org/classic/"  style="color:white!important;">classic site</a> for resources.</p>'
  use_issues_button: true
  use_repository_button: true

repository:
  url: "https://github.com/uds-se/fuzzingbook/"
  path_to_book: "docs/notebooks"
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: false  # Does not support local imports
