name: fuzzingbook
channels:
  - defaults
  - anaconda-fusion
  - conda-forge
  - bjornfjohansson
  - anaconda-platform
dependencies:
  - python=3.6  # "import enforce" doesn't work on Python 3.7
  - matplotlib
  - numpy
  - scipy
  - pandas
  - graphviz
  - autopep8
  - notedown
  - markdown
  - mypy
  - selenium
  - geckodriver
  - django
  - pip:
      - graphviz
      - networkx
      - pydot
      - yapf
      - autopep8
      - svglib
      - jupyter_contrib_nbextensions
      - astor
      - showast
      - enforce
      - z3-solver
      - git+https://github.com/uds-se/pyan#egg=pyan
      - FuzzManager
